import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Provider from "@/components/provider";
import Footer from "@/components/layout/footer";
import { Suspense } from "react";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fontSans.variable}>
      <body className="">
        <Provider>
          <Suspense fallback={<div>Loading...</div>}>
            <Navbar />

            {children}
            <Footer />
          </Suspense>
        </Provider>
      </body>
    </html>
  );
}
